### PR TITLE
Create hebrew.ts

### PR DESCRIPTION
**Pull request by aslanbeily**
Hebrew translation

### CODE REVIEW

**Comment by aslanbeily** [comment]
Any chance for a new build including this translation?)))

**Comment by dmitrykurmanov** [comment]
We will implement it this week

**Comment by aslanbeily** [comment]
Премного благодарен заранее ))

2017-12-13 13:35 GMT+02:00 DUODVK <notifications@github.com>:

**Comment by aslanbeily** [comment]
Hello again,

I do see my file in the source pack, but there are no hebrew translations in 0.98.4
(https://surveyjs.azureedge.net/0.98.4/survey.jquery.js)
Do I need to provide anythig else to see hebrew buttons and texts like (Other)?

Thanks in advance

**Comment by andrewtelnov** [comment]
@aslanbeily The file was not included into webpack. I have just added it. I am sorry about that. It will be here in the next release.

Thank you,
Andrew

**Pull request merged**
